import fs from 'fs/promises';
import path from 'path';
import type { GeneratedFile } from '@/types/deployment';
import type { BlueprintInput, BlueprintVersion } from '@/types/blueprint';
import { getBlueprintVersion } from '@/features/blueprints/blueprint-service';
import { getBlueprintsDir } from '@/features/blueprints/blueprint-loader';
import { generateTfvars, renderTemplate } from './template-engine';
import { createManifest, getGeneratorVersion } from './manifest';
import { ValidationError } from '@/lib/errors';
import { isRelativePathSafe } from '@/lib/path-safety';

export interface GenerationValue {
  value: string | number | boolean;
  sensitive: boolean;
}

export interface GenerationInput {
  blueprintSlug: string;
  blueprintVersion: string;
  deploymentId: string;
  targetDir: string;
  environmentName: string;
  inputs: Record<string, GenerationValue>;
  workspaceId?: string;
}

export interface GenerationResult {
  files: GeneratedFile[];
  warnings: string[];
}

/**
 * Validates user inputs against the blueprint's input schema definitions.
 */
function validateInputs(
  userInputs: Record<string, GenerationValue>,
  blueprintInputs: BlueprintInput[]
): string[] {
  const errors: string[] = [];

  for (const def of blueprintInputs) {
    const inputVal = userInputs[def.name];
    const value = inputVal?.value;
    const hasValue =
      value !== undefined && value !== null && value !== '';

    if (def.required && !hasValue) {
      errors.push(`Missing required input: ${def.name} (${def.label})`);
      continue;
    }

    if (!hasValue) continue;

    // Skip further detailed validation if sensitive value is redacted for previews
    if (inputVal?.sensitive && (value === '********' || value === '[REDACTED]')) {
      continue;
    }

    // Type checking
    switch (def.type) {
      case 'number':
        if (typeof value !== 'number' && isNaN(Number(value))) {
          errors.push(`Input "${def.name}" must be a number`);
        }
        break;
      case 'boolean':
        if (typeof value !== 'boolean' && value !== 'true' && value !== 'false') {
          errors.push(`Input "${def.name}" must be a boolean`);
        }
        break;
      case 'select':
      case 'region':
        if (def.options && def.options.length > 0) {
          const validValues = def.options.map((o) => o.value);
          if (!validValues.includes(String(value))) {
            errors.push(
              `Input "${def.name}" must be one of: ${validValues.join(', ')}`
            );
          }
        }
        break;
      case 'cidr':
        if (typeof value === 'string' && !/^\d{1,3}(\.\d{1,3}){3}\/\d{1,2}$/.test(value)) {
          errors.push(`Input "${def.name}" must be a valid CIDR notation`);
        }
        break;
    }

    // Custom validation
    if (def.validation) {
      const strValue = String(value);
      if (def.validation.min !== undefined && strValue.length < def.validation.min) {
        errors.push(
          def.validation.message ??
            `Input "${def.name}" must be at least ${def.validation.min} characters`
        );
      }
      if (def.validation.max !== undefined && strValue.length > def.validation.max) {
        errors.push(
          def.validation.message ??
            `Input "${def.name}" must be at most ${def.validation.max} characters`
        );
      }
      if (def.validation.pattern) {
        const re = new RegExp(def.validation.pattern);
        if (!re.test(strValue)) {
          errors.push(
            def.validation.message ??
              `Input "${def.name}" does not match required pattern`
          );
        }
      }
    }
  }

  return errors;
}

/**
 * Reads all .tf files from the blueprint version's source directory or database.
 */
async function readBlueprintFiles(
  blueprintSlug: string,
  version: BlueprintVersion
): Promise<GeneratedFile[]> {
  if (version.files) {
    return Object.entries(version.files).map(([filePath, content]) => ({
      path: filePath,
      content,
    }));
  }

  const blueprintsDir = getBlueprintsDir();
  const sourceDir = path.join(blueprintsDir, blueprintSlug, version.sourceDir);

  let entries: string[];

  try {
    entries = await fs.readdir(sourceDir);
  } catch {
    throw new Error(
      `Blueprint source directory not found: ${sourceDir}`
    );
  }

  const files: GeneratedFile[] = [];
  for (const entry of entries) {
    const filePath = path.join(sourceDir, entry);
    const stat = await fs.stat(filePath);
    if (!stat.isFile()) continue;

    const content = await fs.readFile(filePath, 'utf-8');
    files.push({ path: entry, content });
  }

  return files;
}

/**
 * Generates a README.md for the deployment.
 */
function generateReadme(input: GenerationInput, version: BlueprintVersion): GeneratedFile {
  const lines: string[] = [
    `# ${input.blueprintSlug} — ${input.environmentName}`,
    '',
    `> Auto-generated by Stacksmith (generator v${getGeneratorVersion()})`,
    `> Blueprint: \`${input.blueprintSlug}@${input.blueprintVersion}\``,
    `> Deployment ID: \`${input.deploymentId}\``,
    `> Generated at: ${new Date().toISOString()}`,
    '',
    '## Inputs',
    '',
    '| Variable | Value |',
    '|----------|-------|',
  ];

  for (const def of version.inputs) {
    const inputVal = input.inputs[def.name];
    const isSensitive = inputVal?.sensitive ?? (def.type === 'sensitive');
    const displayValue = isSensitive ? '********' : String(inputVal?.value ?? def.default ?? '');
    lines.push(`| \`${def.name}\` | ${displayValue} |`);
  }

  if (version.outputs.length > 0) {
    lines.push('', '## Outputs', '');
    lines.push('| Name | Description |');
    lines.push('|------|-------------|');
    for (const out of version.outputs) {
      lines.push(`| \`${out.name}\` | ${out.description} |`);
    }
  }

  lines.push('', '---', '', 'Warning: do not edit files tracked by `.stacksmith.json` manually.', '');

  return { path: 'README.md', content: lines.join('\n') };
}

/**
 * Main generation function.
 * Deterministic: same inputs produce the same outputs (aside from timestamp).
 */
export async function generate(input: GenerationInput): Promise<GenerationResult> {
  // Validate target dir
  if (!isRelativePathSafe(input.targetDir)) {
    throw new ValidationError('Invalid target directory', {
      targetDir: ['Target directory contains unsafe path segments'],
    });
  }

  // Load the blueprint version
  const version = await getBlueprintVersion(input.blueprintSlug, input.blueprintVersion, input.workspaceId);

  // Validate inputs
  const validationErrors = validateInputs(input.inputs, version.inputs);
  if (validationErrors.length > 0) {
    throw new ValidationError('Input validation failed', {
      inputs: validationErrors,
    });
  }

  const warnings: string[] = [];
  const files: GeneratedFile[] = [];

  // 1. Read blueprint .tf files (these use Terraform variables, not template substitution)
  const blueprintFiles = await readBlueprintFiles(input.blueprintSlug, version);
  for (const bf of blueprintFiles) {
    // Apply template rendering only for files that contain {{placeholders}}
    // Standard .tf files use Terraform variables and don't need substitution
    if (/\{\{[a-zA-Z_][a-zA-Z0-9_]*\}\}/.test(bf.content)) {
      // Reject sensitive placeholders
      const placeholders = new Set<string>();
      let match: RegExpExecArray | null;
      const pattern = /\{\{([a-zA-Z_][a-zA-Z0-9_]*)\}\}/g;
      while ((match = pattern.exec(bf.content)) !== null) {
        placeholders.add(match[1]);
      }
      for (const p of placeholders) {
        if (input.inputs[p]?.sensitive) {
          throw new ValidationError('Security violation', {
            inputs: [`Cannot render sensitive input "${p}" in template file "${bf.path}". Use Terraform variables instead to keep secrets secure.`]
          });
        }
      }

      // Convert Record<string, GenerationValue> to Record<string, string | number | boolean> for renderTemplate
      const rawInputs: Record<string, string | number | boolean> = {};
      for (const [k, v] of Object.entries(input.inputs)) {
        rawInputs[k] = v.value;
      }

      const result = renderTemplate(bf.content, rawInputs);
      if (result.missingVariables.length > 0) {
        warnings.push(
          `File "${bf.path}" has unresolved placeholders: ${result.missingVariables.join(', ')}`
        );
      }
      files.push({
        path: path.posix.join(input.targetDir, bf.path),
        content: result.content,
      });
    } else {
      files.push({
        path: path.posix.join(input.targetDir, bf.path),
        content: bf.content,
      });
    }
  }

  // 2. Generate terraform.tfvars from user inputs (excluding sensitive inputs to prevent committing secrets to git)
  const nonSensitiveInputs: Record<string, string | number | boolean> = {};
  for (const def of version.inputs) {
    const inputVal = input.inputs[def.name];
    if (inputVal && !inputVal.sensitive && inputVal.value !== undefined && inputVal.value !== null) {
      nonSensitiveInputs[def.name] = inputVal.value;
    }
  }

  const tfvarsContent = generateTfvars(nonSensitiveInputs);
  files.push({
    path: path.posix.join(input.targetDir, 'terraform.tfvars'),
    content: tfvarsContent,
  });

  // 3. Generate README.md
  const readme = generateReadme(input, version);
  files.push({
    path: path.posix.join(input.targetDir, readme.path),
    content: readme.content,
  });

  // 4. Generate .stacksmith.json manifest (legacy .infrapack.json remains readable)
  const managedPaths = files.map((f) => f.path);
  const manifestFile = createManifest({
    blueprintSlug: input.blueprintSlug,
    blueprintVersion: input.blueprintVersion,
    deploymentId: input.deploymentId,
    managedFiles: [
      ...managedPaths,
      path.posix.join(input.targetDir, '.stacksmith.json'),
    ],
  });
  files.push({
    path: path.posix.join(input.targetDir, manifestFile.path),
    content: manifestFile.content,
  });

  return { files, warnings };
}
