/**
 * Safe template engine using {{variable}} placeholders only.
 * NO eval(), NO Function constructor, NO template literals with user input.
 */

const PLACEHOLDER_PATTERN = /\{\{([a-zA-Z_][a-zA-Z0-9_]*)\}\}/g;

export interface TemplateResult {
  content: string;
  /** Placeholders found in the template that were replaced */
  usedVariables: string[];
  /** Variables provided but not found in the template */
  unusedVariables: string[];
  /** Placeholders found in the template but not provided */
  missingVariables: string[];
}

/**
 * Replaces all {{variable}} placeholders in a template with provided values.
 * Returns the processed content and diagnostics about variable usage.
 */
export function renderTemplate(
  template: string,
  variables: Record<string, string | number | boolean>
): TemplateResult {
  const foundPlaceholders = new Set<string>();
  const providedKeys = new Set(Object.keys(variables));

  // Find all placeholders in the template
  let match: RegExpExecArray | null;
  const pattern = new RegExp(PLACEHOLDER_PATTERN.source, 'g');
  while ((match = pattern.exec(template)) !== null) {
    foundPlaceholders.add(match[1]);
  }

  // Perform replacement
  const content = template.replace(PLACEHOLDER_PATTERN, (_full, varName: string) => {
    if (varName in variables) {
      return String(variables[varName]);
    }
    // Leave unresolved placeholders as-is
    return `{{${varName}}}`;
  });

  const usedVariables = [...foundPlaceholders].filter((v) => providedKeys.has(v));
  const unusedVariables = [...providedKeys].filter((v) => !foundPlaceholders.has(v));
  const missingVariables = [...foundPlaceholders].filter((v) => !providedKeys.has(v));

  if (unusedVariables.length > 0) {
    console.warn(
      `[template-engine] Unused variables: ${unusedVariables.join(', ')}`
    );
  }

  return { content, usedVariables, unusedVariables, missingVariables };
}

/**
 * Validates that all required placeholders are filled.
 * Throws if any placeholders remain unresolved.
 */
export function renderTemplateStrict(
  template: string,
  variables: Record<string, string | number | boolean>
): string {
  const result = renderTemplate(template, variables);
  if (result.missingVariables.length > 0) {
    throw new Error(
      `Template has unresolved placeholders: ${result.missingVariables.join(', ')}`
    );
  }
  return result.content;
}

/**
 * Generates terraform.tfvars content from a map of user inputs.
 * Properly formats values based on their type (string, number, boolean).
 */
export function generateTfvars(
  inputs: Record<string, string | number | boolean>
): string {
  const lines: string[] = [
    '# Auto-generated by InfraPack',
    `# Generated at: ${new Date().toISOString()}`,
    '# Do not edit manually — changes will be overwritten on regeneration.',
    '',
  ];

  const sortedKeys = Object.keys(inputs).sort();

  const isListKey = (key: string): boolean => {
    const listKeys = ['policy_arns', 'public_subnet_cidrs', 'private_subnet_cidrs', 'subnet_ids', 'alb_subnet_ids', 'allowed_security_group_ids'];
    return listKeys.includes(key) || key.endsWith('_cidrs') || key.endsWith('_arns') || key.endsWith('_ids');
  };

  const isMapKey = (key: string): boolean => {
    const mapKeys = ['tags', 'environment_variables'];
    return mapKeys.includes(key) || key.endsWith('_tags');
  };

  for (const key of sortedKeys) {
    const value = inputs[key];

    if (typeof value === 'boolean') {
      lines.push(`${key} = ${value}`);
    } else if (typeof value === 'number') {
      lines.push(`${key} = ${value}`);
    } else if (isListKey(key)) {
      // Parse comma-separated list
      const strVal = String(value).trim();
      let elements: string[] = [];
      if (strVal.startsWith('[') && strVal.endsWith(']')) {
        // Strip outer brackets and split
        elements = strVal.slice(1, -1).split(',').map((e) => e.trim().replace(/^["']|["']$/g, '')).filter(Boolean);
      } else {
        elements = strVal.split(',').map((e) => e.trim()).filter(Boolean);
      }
      const formattedList = `[${elements.map((e) => `"${e.replace(/\\/g, '\\\\').replace(/"/g, '\\"')}"`).join(', ')}]`;
      lines.push(`${key} = ${formattedList}`);
    } else if (isMapKey(key)) {
      // Parse comma-separated key=value pairs
      const strVal = String(value).trim();
      const pairs = strVal.split(',').map((p) => p.trim()).filter(Boolean);
      const mapLines: string[] = [];
      for (const pair of pairs) {
        const eqIdx = pair.indexOf('=');
        if (eqIdx > 0) {
          const k = pair.substring(0, eqIdx).trim();
          const v = pair.substring(eqIdx + 1).trim().replace(/^["']|["']$/g, '');
          const escapedV = v.replace(/\\/g, '\\\\').replace(/"/g, '\\"');
          mapLines.push(`  "${k}" = "${escapedV}"`);
        }
      }
      if (mapLines.length > 0) {
        lines.push(`${key} = {\n${mapLines.join('\n')}\n}`);
      } else {
        lines.push(`${key} = {}`);
      }
    } else {
      // Normal String — escape backslashes and quotes for HCL
      const escaped = String(value)
        .replace(/\\/g, '\\\\')
        .replace(/"/g, '\\"');
      lines.push(`${key} = "${escaped}"`);
    }
  }

  lines.push(''); // trailing newline
  return lines.join('\n');
}
