name: Feature request
description: Suggest an improvement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem being solved
    validations:
      required: true
  - type: textarea
    id: behavior
    attributes:
      label: Proposed behavior
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
  - type: dropdown
    id: edition
    attributes:
      label: Affects
      options: ["self-hosted", "hosted", "both", "unsure"]
